spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true


  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ENC(RhrvH0WDF8iUyLbYo8GhHGvtGkgXYgxKVyExHiU8WqU=)
      secret-key: ENC(CBXSxecabu5dHhwxHE85cEnuzChL0vNVTig8szl1ErrgeQSTO4Xfc61e6vK+JrDEDUvlRgss5fg=)
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: puddybucket
jwt:
  secret-key: ENC(qBptcytc75l909BnyVcmGxm8E/7EI48ZTpHCkluUA5f5FNT3VvfOtmHdHfubfmhwa8wqyeVvSImInp65qdCie1eH8jOTvdsdzYiFeFCUai8=)


