spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ENC(JPJP3xGryfr7BOeyE7fGSrEU7mbIALuM4+zS1u6ktsM=)
      secret-key: ENC(J/FWXsaZz2e8TzbvBeU3CjC1EwoXfHiStRwbONeTnsjmNjySVpNL1KLUkXNE+E607oViUUzSYWg=)
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: puddy-bucket
jwt:
  secret-key: ENC(qBptcytc75l909BnyVcmGxm8E/7EI48ZTpHCkluUA5f5FNT3VvfOtmHdHfubfmhwa8wqyeVvSImInp65qdCie1eH8jOTvdsdzYiFeFCUai8=)


